services:
  server:
    image: server
    environment: 
      - HOST=${HOST}
      - PORT=${PORT}

  test:
    image: test
    environment: 
      - HOST=server
      - PORT=${PORT}
    depends_on:
      - server
