services:
  server:
    image: server
    environment: 
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - "8080:8080" 

  test:
    image: test
    environment: 
      - HOST=server
      - PORT=8080
    depends_on:
      - server
